Repository ansible/ansible-creator, pull requests merged in 2024-12, with the labels that each got.

#336 Enable scheduled GHA runs
  .github/workflows/tox.yml
  .gitignore
Labels: skip-changelog

#320 Add support to scaffold devcontainer
  .config/dictionary.txt
  .github/dependabot.yml
  .github/workflows/tox.yml
  .tool-versions
  package-lock.json
  package.json
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/constants.py
  src/ansible_creator/resources/common/devcontainer/.devcontainer/devcontainer.json.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/docker/devcontainer.json.j2
  src/ansible_creator/subcommands/add.py
  tests/fixtures/collection/testorg/testcol/.devcontainer/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.devcontainer/docker/devcontainer.json
  tests/fixtures/project/playbook_project/.devcontainer/devcontainer.json
  tests/fixtures/project/playbook_project/.devcontainer/docker/devcontainer.json
  tests/units/test_add.py
  tox.ini
Labels: enhancement

#340 Add support to scaffold execution environment sample file
  .config/dictionary.txt
  src/ansible_creator/arg_parser.py
  src/ansible_creator/constants.py
  src/ansible_creator/resources/common/execution-environment/execution-environment.yml.j2
  src/ansible_creator/subcommands/add.py
  src/ansible_creator/types.py
  tests/fixtures/common/execution-environment/execution-environment.yml
  tests/units/test_add.py
Labels: enhancement

#341 Corrections to the lookup plugin template
  src/ansible_creator/resources/collection_project/plugins/lookup/hello_world.py.j2
  tests/fixtures/collection/testorg/testcol/plugins/lookup/hello_world.py
Labels: skip-changelog

#344 Changes to the lookup template to encounter tox-ansible sanity check failures
  src/ansible_creator/resources/collection_project/plugins/lookup/hello_world.py.j2
  tests/fixtures/collection/testorg/testcol/plugins/lookup/hello_world.py
Labels: bug
