Repository ansible/ansible-creator, pull requests merged in 2024-02, with the labels that each got.

#75 Unpin `jinja2` requirements
  .config/constraints.txt
  .config/docs-requirements.in
  .config/requirements.in
  .config/test-requirements.in
  .github/dependabot.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  cspell.config.yaml
  pyproject.toml
  tox.ini
Labels: bug

#81 Rename requirements files
  .config/requirements-docs.in
  .config/requirements-test.in
  pyproject.toml
Labels: skip-changelog

#80 Drop support for Python 3.9
  .config/constraints.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_creator/utils.py
  tox.ini
Labels: enhancement

#85 Review codecov config
  .github/workflows/tox.yml
Labels: skip-changelog

#87 More codecov fixes
  codecov.yml
Labels: skip-changelog

#86 Update dependencies to include new mkdocs-ansible branding
  .config/constraints.txt
Labels: skip-changelog

#89 Test for reusing secrets
  .github/workflows/release.yml
Labels: skip-changelog

#94 Disable codecov CI failure check
  .github/workflows/tox.yml
Labels: skip-changelog
