Repository ansible/ansible-creator, pull requests merged in 2024-11, with the labels that each got.

#309 Add deprecation message for `force` flag
  src/ansible_creator/arg_parser.py
  src/ansible_creator/subcommands/init.py
Labels: skip-changelog

#312 Update upstream docs to reflect CLI changes
  docs/installing.md
Labels: documentation, enhancement

#316 Add support for py313
  pyproject.toml
Labels: enhancement

#315 Update Invalid Link in README -> Release Notes
  src/ansible_creator/resources/collection_project/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
  tests/fixtures/collection/testorg/testcol/README.md
  tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Labels: bug

#314 Add test and production inventory group to the playbook project
  src/ansible_creator/resources/playbook_project/inventory/group_vars/db_servers.yml.j2
  src/ansible_creator/resources/playbook_project/inventory/group_vars/production.yml.j2
  src/ansible_creator/resources/playbook_project/inventory/group_vars/test.yml.j2
  src/ansible_creator/resources/playbook_project/inventory/hosts.yml.j2
  tests/fixtures/project/playbook_project/inventory/group_vars/db_servers.yml
  tests/fixtures/project/playbook_project/inventory/group_vars/production.yml
  tests/fixtures/project/playbook_project/inventory/group_vars/test.yml
  tests/fixtures/project/playbook_project/inventory/hosts.yml
Labels: enhancement

#305 Add support for add subcommand to scaffold devfile resources
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/subcommands/add.py
  src/ansible_creator/types.py
  tests/fixtures/common/devfile/devfile.yaml
  tests/units/test_add.py
Labels: enhancement

#317 Update upstream doc with add subcommand details in installing.md
  docs/installing.md
Labels: documentation, enhancement

#326 Remove type for self
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_creator/arg_parser.py
  src/ansible_creator/cli.py
  src/ansible_creator/config.py
  src/ansible_creator/exceptions.py
  src/ansible_creator/output.py
  src/ansible_creator/resources/collection_project/plugins/filter/hello_world.py.j2
  src/ansible_creator/subcommands/add.py
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/templar.py
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
  tests/units/test_init.py
Labels: skip-changelog

#329 Clean up for upstream docs for add subcommand and devfile resource type
  docs/installing.md
Labels: documentation, skip-changelog

#327 Scaffold lookup plugin through add subcommand
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/resources/collection_project/plugins/lookup/__init__.py.j2
  src/ansible_creator/resources/collection_project/plugins/lookup/hello_world.py.j2
  src/ansible_creator/subcommands/add.py
  src/ansible_creator/types.py
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/plugins/lookup/__init__.py
  tests/fixtures/collection/testorg/testcol/plugins/lookup/hello_world.py
  tests/units/test_add.py
Labels: enhancement

#332 Scaffold filter plugin through add subcommand
  src/ansible_creator/arg_parser.py
  src/ansible_creator/resources/collection_project/plugins/filter/hello_world.py.j2
  src/ansible_creator/subcommands/add.py
  tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
  tests/units/test_add.py
Labels: enhancement
