Repository ansible/ansible-creator, pull requests merged in 2024-04, with the labels that each got.

#116 Use python3 executable
  .github/workflows/release.yml
  .github/workflows/tox.yml
  src/ansible_creator/__main__.py
Labels: skip-changelog

#118 update init-path behaviour
  .config/constraints.txt
  src/ansible_creator/subcommands/init.py
  tests/integration/test_init.py
  tests/units/test_init.py
Labels: bug

#123 Add a test and update documentation regarding `--init-path` updates
  docs/installing.md
  tests/units/test_init.py
Labels: skip-changelog

#125 fix: replace automation hub workflow secret with release_galaxy secret
  src/ansible_creator/resources/new_collection/.github/workflows/release.yml.j2
  tests/fixtures/collection/testorg/testcol/.github/workflows/release.yml
Labels: bug

#128 do not send output args to config class
  src/ansible_creator/cli.py
  src/ansible_creator/config.py
  src/ansible_creator/output.py
  test.log
  tests/units/test_basic.py
  tests/units/test_init.py
Labels: skip-changelog

#131 Delete test.log
  test.log
Labels: skip-changelog

#132 Add mkdocs macro for recommended installation
  .config/requirements-docs.in
  docs/installing.md
  mkdocs.yml
Labels: bug

#135 Make test output consistent (COLUMNS)
  .gitignore
  src/ansible_creator/output.py
  tox.ini
Labels: skip-changelog

#133 Update documentation for ansible-project scaffolding
  docs/installing.md
Labels: documentation, skip-changelog

#136 Fail if coverage goes down
  .github/workflows/tox.yml
Labels: skip-changelog

#134 Do not fail if `init-path` exists but is empty
  src/ansible_creator/subcommands/init.py
  tests/integration/test_init.py
  tests/units/test_init.py
Labels: bug

#138 Adds `build-import` job in GHA workflows and includes `flake8` hook in pre-commit-config for collection scaffolding
  .prettierignore
  src/ansible_creator/resources/new_collection/.github/workflows/tests.yml.j2
  src/ansible_creator/resources/new_collection/.pre-commit-config.yaml.j2
  tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
  tests/fixtures/collection/testorg/testcol/.pre-commit-config.yaml
Labels: enhancement

#142 Global vars and common resources
  .gitignore
  src/ansible_creator/constants.py
  src/ansible_creator/resources/ansible_project/.devcontainer/podman/devcontainer.json
  src/ansible_creator/resources/ansible_project/ansible-navigator.yml.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/devcontainer.json.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/docker/devcontainer.json.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
  src/ansible_creator/resources/new_collection/.devcontainer/docker/devcontainer.json
  src/ansible_creator/resources/new_collection/.devcontainer/podman/devcontainer.json
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/.devcontainer/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.devcontainer/docker/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
  tests/fixtures/project/ansible_project/.devcontainer/devcontainer.json
  tests/fixtures/project/ansible_project/.devcontainer/docker/devcontainer.json
  tests/fixtures/project/ansible_project/.devcontainer/podman/devcontainer.json
  tests/fixtures/project/ansible_project/ansible-navigator.yml
Labels: enhancement

#143 Add devfile to collection and playbook projects
  .config/dictionary.txt
  src/ansible_creator/constants.py
  src/ansible_creator/resources/common/devfile/devfile.yaml.j2
  src/ansible_creator/subcommands/init.py
  tests/fixtures/collection/testorg/testcol/devfile.yaml
  tests/fixtures/project/ansible_project/devfile.yaml
Labels: enhancement

#145 Update docs and README to the latest directory structure
  docs/installing.md
  src/ansible_creator/resources/ansible_project/README.md.j2
  tests/fixtures/project/ansible_project/README.md
Labels: documentation, skip-changelog

#146 remove unused constants
  src/ansible_creator/constants.py
  tests/units/test_basic.py
Labels: skip-changelog

#150 Add gitignore support
  .config/dictionary.txt
  src/ansible_creator/compat.py
  src/ansible_creator/resources/common/gitignore/.gitignore.j2
  src/ansible_creator/resources/common/gitignore/__meta__.yml
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/.gitignore
  tests/fixtures/project/ansible_project/.gitignore
Labels: enhancement

#151 remove unused method and add unit test
  src/ansible_creator/utils.py
  tests/units/test_basic.py
Labels: skip-changelog

#156 Update devfile image
  src/ansible_creator/constants.py
  tests/fixtures/collection/testorg/testcol/devfile.yaml
  tests/fixtures/project/ansible_project/devfile.yaml
Labels: bug
