Repository ansible/ansible-creator, pull requests merged in 2024-01, with the labels that each got.

#50 Add integration tests
  .config/requirements-test.txt
  .github/workflows/tox.yml
  README.md
  src/ansible_creator/templar.py
  src/ansible_creator/validators.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/test_init.py
  tests/units/conftest.py
  tests/units/test_init.py
  tox.ini
Labels: skip-changelog

#58 More github workflow updates
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .pre-commit-config.yaml
Labels: skip-changelog

#57 Assorted README updates
  README.md
Labels: skip-changelog

#60 Fix github workflow for release
  .github/workflows/release.yml
Labels: skip-changelog

#63 Update index.md
  docs/index.md
Labels: skip-changelog

#65 Add GitHub Action specific files
  src/ansible_creator/resources/new_collection/.github/workflows/release.yml.j2
  src/ansible_creator/resources/new_collection/.github/workflows/test.yml.j2
  src/ansible_creator/resources/new_collection/changelogs/config.yaml
  src/ansible_creator/resources/new_collection/galaxy.yml.j2
  src/ansible_creator/resources/new_collection/meta/runtime.yml
  src/ansible_creator/resources/new_collection/tox-ansible.ini.j2
  tests/fixtures/collection/testorg/testcol/.github/workflows/release.yml
  tests/fixtures/collection/testorg/testcol/.github/workflows/test.yml
  tests/fixtures/collection/testorg/testcol/changelogs/config.yaml
  tests/fixtures/collection/testorg/testcol/galaxy.yml
  tests/fixtures/collection/testorg/testcol/meta/runtime.yml
  tests/fixtures/collection/testorg/testcol/tox-ansible.ini
Labels: enhancement

#67 Update RTD with GHA workflow and testing information
  .config/dictionary.txt
  docs/installing.md
Labels: minor

#71 Update creator URL in scaffolded galaxy.yml
  src/ansible_creator/resources/new_collection/galaxy.yml.j2
  tests/fixtures/collection/testorg/testcol/galaxy.yml
Labels: bug

#72 update development status in pyproject.toml
  pyproject.toml
Labels: skip-changelog

#74 Update badges to link to PyPI
  README.md
Labels: skip-changelog
