Repository ansible/ansible-creator, pull requests merged in 2024-09, with the labels that each got.

#283 Add communication details
  README.md
  docs/contributing.md
  mkdocs.yml
Labels: documentation, enhancement

#290 Cleanup of init functionality
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/resources/common/gitignore/__meta__.yml
  src/ansible_creator/resources/playbook_project/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/roles/run/README.md.j2
  src/ansible_creator/resources/playbook_project/site.yml.j2
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/types.py
  src/ansible_creator/utils.py
  tests/units/test_basic.py
  tests/units/test_init.py
Labels: enhancement

#291 Docs: remove IRC/ML/google.groups remnants
  src/ansible_creator/resources/collection_project/docs/docsite/links.yml.j2
  tests/fixtures/collection/testorg/testcol/docs/docsite/links.yml
Labels: documentation, skip-changelog

#293 Unify scaffolding code
  src/ansible_creator/subcommands/init.py
  tests/integration/test_init.py
  tests/units/test_basic.py
  tests/units/test_init.py
Labels: bug

#296 Correct the bullhorn link
  src/ansible_creator/resources/collection_project/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
  tests/fixtures/collection/testorg/testcol/README.md
  tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Labels: skip-changelog

#294 Split Copier into Walker and Copier steps
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/utils.py
  tests/units/test_utils.py
Labels: enhancement
