Repository ansible/ansible-creator, pull requests merged in 2024-03, with the labels that each got.

#105 Update ack.yml
  .github/workflows/ack.yml
Labels: skip-changelog

#99 Scaffold a sample ansible role and playbook in existing collection: init
  .config/dictionary.txt
  .prettierignore
  src/ansible_creator/resources/new_collection/playbooks/sample_playbook_1.yml.j2
  src/ansible_creator/resources/new_collection/playbooks/sample_playbook_2.yml.j2
  src/ansible_creator/resources/new_collection/roles/run/README.md.j2
  src/ansible_creator/resources/new_collection/roles/run/defaults/main.yml
  src/ansible_creator/resources/new_collection/roles/run/files/.keep
  src/ansible_creator/resources/new_collection/roles/run/handlers/main.yml
  src/ansible_creator/resources/new_collection/roles/run/meta/main.yml.j2
  src/ansible_creator/resources/new_collection/roles/run/tasks/main.yml
  src/ansible_creator/resources/new_collection/roles/run/templates/.keep
  src/ansible_creator/resources/new_collection/roles/run/tests/inventory
  src/ansible_creator/resources/new_collection/roles/run/vars/main.yml
  tests/fixtures/collection/testorg/testcol/playbooks/sample_playbook_1.yml
  tests/fixtures/collection/testorg/testcol/playbooks/sample_playbook_2.yml
  tests/fixtures/collection/testorg/testcol/roles/run/README.md
  tests/fixtures/collection/testorg/testcol/roles/run/defaults/main.yml
  tests/fixtures/collection/testorg/testcol/roles/run/files/.keep
  tests/fixtures/collection/testorg/testcol/roles/run/handlers/main.yml
  tests/fixtures/collection/testorg/testcol/roles/run/meta/main.yml
  tests/fixtures/collection/testorg/testcol/roles/run/tasks/main.yml
  tests/fixtures/collection/testorg/testcol/roles/run/templates/.keep
  tests/fixtures/collection/testorg/testcol/roles/run/tests/inventory
  tests/fixtures/collection/testorg/testcol/roles/run/vars/main.yml
Labels: enhancement

#102 Add documentation for playbook and role scaffolding in existing collection
  docs/installing.md
Labels: documentation, skip-changelog

#107 Remove playbook scaffolding from collection init
  .config/dictionary.txt
  .prettierignore
  docs/installing.md
  src/ansible_creator/resources/new_collection/playbooks/sample_playbook_1.yml.j2
  src/ansible_creator/resources/new_collection/playbooks/sample_playbook_2.yml.j2
  tests/fixtures/collection/testorg/testcol/playbooks/sample_playbook_1.yml
  tests/fixtures/collection/testorg/testcol/playbooks/sample_playbook_2.yml
Labels: skip-changelog

#111 Suggest adt installation
  docs/installing.md
Labels: documentation, skip-changelog
