Repository ansible/ansible-creator, pull requests merged in 2024-06, with the labels that each got.

#213 chore: Update tox.ini
  tox.ini
Labels: skip-changelog

#215 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#216 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#218 chore: Update .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: skip-changelog

#220 Improve collection root detection
  src/ansible_creator/resources/new_collection/changelogs/config.yaml.j2
  src/ansible_creator/resources/new_collection/docs/docsite/links.yml.j2
  src/ansible_creator/resources/new_collection/extensions/molecule/utils/vars/vars.yml
  src/ansible_creator/resources/new_collection/tests/unit/test_basic.py.j2
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/extensions/molecule/utils/vars/vars.yml
Labels: bug

#223 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#224 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#225 Add known first party
  pyproject.toml
  tests/units/test_init.py
Labels: skip-changelog

#228 chore: Update tox.ini
  tox.ini
Labels: skip-changelog

#229 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#232 Adding collection name requirement checks
  src/ansible_creator/config.py
  src/ansible_creator/constants.py
  tests/units/test_init.py
Labels: enhancement

#233 Assorted CI fixes for scaffolded content
  pyproject.toml
  src/ansible_creator/resources/ansible_project/collections/requirements.yml.j2
  src/ansible_creator/resources/new_collection/README.md.j2
  src/ansible_creator/resources/new_collection/extensions/molecule/utils/vars/vars.yml
  src/ansible_creator/resources/new_collection/meta/runtime.yml
  src/ansible_creator/resources/new_collection/plugins/filter/hello_world.py.j2
  src/ansible_creator/resources/new_collection/tests/unit/__init__.py
  tests/fixtures/collection/testorg/testcol/README.md
  tests/fixtures/collection/testorg/testcol/extensions/molecule/utils/vars/vars.yml
  tests/fixtures/collection/testorg/testcol/meta/runtime.yml
  tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
  tests/fixtures/collection/testorg/testcol/tests/unit/__init__.py
  tests/fixtures/project/ansible_project/collections/requirements.yml
Labels: bug

#234 Remove useless suppressions and set pylint to use py310
  .pre-commit-config.yaml
  src/ansible_creator/compat.py
Labels: skip-changelog

#235 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
  src/ansible_creator/compat.py
  src/ansible_creator/config.py
  src/ansible_creator/output.py
  src/ansible_creator/utils.py
  tests/units/test_init.py
Labels: skip-changelog

#237 Add RH auth extension recommendation
  src/ansible_creator/constants.py
  src/ansible_creator/resources/ansible_project/.vscode/extensions.json
  src/ansible_creator/resources/common/devcontainer/.devcontainer/devcontainer.json.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/docker/devcontainer.json.j2
  src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
  src/ansible_creator/resources/common/devfile/devfile.yaml.j2
  src/ansible_creator/resources/common/vscode/.vscode/extensions.json.j2
  src/ansible_creator/resources/new_collection/.vscode/extensions.json
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/templar.py
  src/ansible_creator/types.py
  src/ansible_creator/utils.py
  tests/fixtures/collection/testorg/testcol/.devcontainer/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.devcontainer/docker/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
  tests/fixtures/collection/testorg/testcol/.vscode/extensions.json
  tests/fixtures/project/ansible_project/.devcontainer/devcontainer.json
  tests/fixtures/project/ansible_project/.devcontainer/docker/devcontainer.json
  tests/fixtures/project/ansible_project/.devcontainer/podman/devcontainer.json
  tests/fixtures/project/ansible_project/.vscode/extensions.json
  tests/units/test_templar.py
Labels: enhancement

#239 Remove flake8
  .config/pydoclint-baseline.txt
  .config/requirements-test.in
  .flake8
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  pyproject.toml
Labels: skip-changelog

#240 Exclude the baseline from remove-tabs
  .pre-commit-config.yaml
Labels: skip-changelog

#241 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog
