Repository ansible/ansible-creator, pull requests merged in 2024-07, with the labels that each got.

#248 Regenerated cspell dictionary with accurate project terms
  .config/dictionary.txt
Labels: bug

#253 Refactor CLI
  .config/dictionary.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  README.md
  docs/index.md
  docs/installing.md
  src/ansible_creator/arg_parser.py
  src/ansible_creator/cli.py
  src/ansible_creator/compat.py
  tests/integration/test_init.py
  tests/units/test_argparse_help.py
  tests/units/test_basic.py
  tests/units/test_output.py
Labels: enhancement

#258 avoid hardcoded path in test conf
  tests/conftest.py
  tests/units/test_basic.py
Labels: bug

#263 chore: Update .config/dictionary.txt
  .config/dictionary.txt
Labels: skip-changelog

#265 chore: Update .github/workflows/release.yml
  .github/workflows/release.yml
Labels: skip-changelog

#266 chore: Update .sonarcloud.properties
  .sonarcloud.properties
Labels: skip-changelog

#267 chore: Update .vscode/extensions.json
  .vscode/extensions.json
Labels: skip-changelog

#268 Simplify the code base
  .config/dictionary.txt
  .sonarlint/connectedMode.json
  .vscode/settings.json
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/subcommands/init.py
  src/ansible_creator/utils.py
  tests/units/test_basic.py
  tests/units/test_init.py
  tests/units/test_utils.py
Labels: skip-changelog

#269 Additional tests, minor fixes
  src/ansible_creator/output.py
  src/ansible_creator/resources/new_collection/tests/unit/test_basic.py.j2
  tests/fixtures/collection/testorg/testcol/tests/unit/test_basic.py
  tests/units/test_output.py
Labels: skip-changelog

#272 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog
