Repository ansible/ansible-creator, pull requests merged in 2025-03, with the labels that each got.

#370 Refactor developer docs
  docs/collection_creation.md
  docs/content_creation.md
  docs/index.md
  docs/installing.md
  mkdocs.yml
Labels: enhancement

#368 Scaffold an execution-environment project using init subcommand
  src/ansible_creator/arg_parser.py
  src/ansible_creator/resources/execution_env_project/.github/workflows/ci.yml.j2
  src/ansible_creator/resources/execution_env_project/.gitignore
  src/ansible_creator/resources/execution_env_project/README.md
  src/ansible_creator/resources/execution_env_project/execution-environment.yml.j2
  src/ansible_creator/subcommands/init.py
  tests/fixtures/project/ee_project/.github/workflows/ci.yml
  tests/fixtures/project/ee_project/.gitignore
  tests/fixtures/project/ee_project/README.md
  tests/fixtures/project/ee_project/execution-environment.yml
  tests/integration/test_init.py
  tests/units/test_init.py
Labels: enhancement

#377 Scaffold a test plugin in an existing ansible collection using add subcommand.
  src/ansible_creator/arg_parser.py
  src/ansible_creator/resources/collection_project/plugins/test/hello_world.py.j2
  src/ansible_creator/subcommands/add.py
  tests/fixtures/collection/testorg/testcol/plugins/test/hello_world.py
  tests/units/test_add.py
Labels: enhancement

#388 Ensure ansible-creator references current devspaces container
  .config/dictionary.txt
  src/ansible_creator/constants.py
  tests/fixtures/collection/testorg/testcol/devfile.yaml
  tests/fixtures/common/devfile/devfile.yaml
  tests/fixtures/project/playbook_project/devfile.yaml
Labels: enhancement, dependencies

#386 Updated the Installing.md docs and updated the sample_test.py.j2 file
  docs/installing.md
  src/ansible_creator/resources/collection_project/plugins/test/sample_test.py.j2
  tests/fixtures/collection/testorg/testcol/plugins/test/sample_test.py
  tests/units/test_init.py
Labels: bug, documentation
