Repository ansible/ansible-creator, pull requests merged in 2025-04, with the labels that each got.

#392 Workaround for dependabot improper python version
  .env
  .gitignore
  mise.toml
Labels: skip-changelog

#394 Enable prettier and wrap markdown files
  .pre-commit-config.yaml
  .prettierrc.yaml
  CHANGELOG.md
  README.md
  docs/content_creation.md
  docs/contributing.md
  docs/index.md
  docs/installing.md
  src/ansible_creator/resources/collection_project/CODE_OF_CONDUCT.md
  src/ansible_creator/resources/collection_project/README.md.j2
  src/ansible_creator/resources/execution_env_project/README.md
  src/ansible_creator/resources/playbook_project/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
  tests/fixtures/collection/testorg/testcol/CODE_OF_CONDUCT.md
  tests/fixtures/collection/testorg/testcol/README.md
  tests/fixtures/project/ee_project/README.md
  tests/fixtures/project/playbook_project/README.md
  tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Labels: bug

#393 Update pre-commit hooks
  .config/constraints.txt
  .config/pydoclint-baseline.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  .python-version
  .taplo.toml
  .vscode/extensions.json
  ansible.cfg
  pyproject.toml
  src/ansible_creator/types.py
  tests/units/test_add.py
  tests/units/test_init.py
Labels: skip-changelog

#395 Update readme template links
  src/ansible_creator/resources/collection_project/README.md.j2
  src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
  tests/fixtures/collection/testorg/testcol/README.md
  tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Labels: bug

#401 Fix podman devcontainer
  src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
  tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
  tests/fixtures/project/playbook_project/.devcontainer/podman/devcontainer.json
Labels: bug

#402 Comment out scheduled cron job in github action workflow file
  src/ansible_creator/resources/collection_project/.github/workflows/tests.yml.j2
  src/ansible_creator/resources/playbook_project/.github/workflows/tests.yml.j2
  tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
  tests/fixtures/project/playbook_project/.github/workflows/tests.yml
Labels: bug

#405 Update the TO-DO description in tests.yml fixture
  src/ansible_creator/resources/collection_project/.github/workflows/tests.yml.j2
  src/ansible_creator/resources/playbook_project/.github/workflows/tests.yml.j2
  tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
  tests/fixtures/project/playbook_project/.github/workflows/tests.yml
Labels: skip-changelog

#404 Refactor plugin tests in test_add.py
  .config/pydoclint-baseline.txt
  tests/units/test_add.py
Labels: enhancement
