Repository ansible/ansible-creator, pull requests merged in 2025-06, with the labels that each got.

#419 Add pattern support to an existing collection
  .config/dictionary.txt
  docs/installing.md
  src/ansible_creator/arg_parser.py
  src/ansible_creator/config.py
  src/ansible_creator/resources/common/patterns/sample_pattern/README.md
  src/ansible_creator/resources/common/patterns/sample_pattern/execution_environments/execution_environment.yml
  src/ansible_creator/resources/common/patterns/sample_pattern/meta/pattern.json
  src/ansible_creator/resources/common/patterns/sample_pattern/playbooks/group_vars/all.yml
  src/ansible_creator/resources/common/patterns/sample_pattern/playbooks/site.yml
  src/ansible_creator/subcommands/add.py
  src/ansible_creator/types.py
  src/ansible_creator/utils.py
  tests/units/test_add.py
Labels: enhancement

#429 Chore: Require docstring raises for assert
  .config/pydoclint-baseline.txt
  pyproject.toml
  tests/units/test_add.py
Labels: skip-changelog, chore

#432 Enable yaml syntax highlighting for jinja2 templated files
  .vscode/settings.json
Labels: skip-changelog
